[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.23"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
anvil = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"
base = "https://mainnet.base.org"
baseSepolia = "https://sepolia.base.org"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrumSepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
localhost = { key = "" , url="http://127.0.0.1:8545"}
anvil = { key = "" , url="http://127.0.0.1:8545"}
base = { key = "${BASE_ETHERSCAN_API_KEY}" }
baseSepolia = { key = "${BASE_SEPOLIA_ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARB_ETHERSCAN_API_KEY}", url = "https://api.arbiscan.io/api", chain=42161 }
arbitrumSepolia = { key = "${ARB_SEPOLIA_ETHERSCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api", chain=421614 }